// Generated by CoffeeScript 1.6.3
(function() {
  var kids, square;

  square = function(x) {
    return x * x;
  };

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

}).call(this);
